### PR TITLE
Update README.md: delta upload is supported!

### PR DESCRIPTION
**Pull request by joncarmsft**
The service was updated to support this a long time ago so the FAQ answer should be updated.

### CODE REVIEW

**Comment by lawhelpt** [comment]
Hey @joncarmsft, actually this requires a client change to go in (and a small change on the Windows Store team's API). Check out how the changes will likely look here: https://github.com/microsoft/PackageUploader/compare/delta

Once that is all sorted though, will be very happy to see this PR go in 😄

**Comment by joncarmsft** [comment]
Boo. :( I had taken a look at the code and thought the client was already doing the right things for it to Just Work in how it was calling to submit ranges, the same as the JavaScript client does. Alas.

**Comment by Seann-Murdock** [comment]
No need to close this as we are actively working on adding delta upload support. As @joncarmsft mentioned we designed the client to follow the delta upload pattern so making the switch would require minimal changes.

**Comment by joncarmsft** [comment]
@Seann-Murdock I talked with @lawhelpt about it offline and we decided it makes sense to make the readme edit in his branch. Especially since this uploader supports UWP and XVC, which have differing delta upload support, so the answer actually needs more caveats.

**Pull request closed without merging**
