### PR TITLE
Sanitize sas tokens in logs

### PR DESCRIPTION
**Pull request by alberto-baron**

### CODE REVIEW

**Comment by alberto-baron** [comment]
> Can you update the SDK version on line 34 as well please?

To "SDK-V1.7.1"?

**Review by lawhelpt — APPROVED** [review]

**Comment by Seann-Murdock** [comment]
> > Can you update the SDK version on line 34 as well please?
> 
> To "SDK-V1.7.1"?

Actually, I've got a private build for Fast Package Processing using 1.7.1. Lets use 1.7.2 for this one and then update to 1.7.3  or 1.8.0 once the FPP stuff is ready to go GA.

https://github.com/microsoft/PackageUploader/compare/main...users/semurdoc/enableFPP

**Comment by alberto-baron** [comment]
> > > Can you update the SDK version on line 34 as well please?
> > 
> > 
> > To "SDK-V1.7.1"?
> 
> Actually, I've got a private build for Fast Package Processing using 1.7.1. Lets use 1.7.2 for this one and then update to 1.7.3 or 1.8.0 once the FPP stuff is ready to go GA.
> 
> [main...users/semurdoc/enableFPP](https://github.com/microsoft/PackageUploader/compare/main...users/semurdoc/enableFPP)

Instead of hardcoding the version, I have changed it to use reflection to get the version number from the assembly. That way we can forget about changing it moving forward. What do you think?

**Review by Seann-Murdock — APPROVED** [review]
Looks great! The reflection piece is great.

**Pull request merged**
